### ISSUE TITLE
Question about your latency graph

### ISSUE THREAD

**Issue by dzenilee** [huggingface/optimum-benchmark#112]
@IlyasMoutawwakil Just to be clear, this graph is showing that the AWQ method performs the _worst_ in terms of forward latency/inference time, correct? (from https://github.com/huggingface/optimum-benchmark/tree/main/examples/running-mistrals) 

![image](https://github.com/huggingface/optimum-benchmark/assets/19984169/d665e113-3d8a-42aa-bbbf-92794f456374)

I've been coming across conflicting information around the impact of quantization on inference time, so just checking. For example, on https://huggingface.co/docs/transformers/main/en/quantization, it mentions 

> AWQ quantization can also be combined with FlashAttention-2 to **further** accelerate inference. 

(emphasis on "further") - implying AWQ was supposed to accelerate inference. But your graph seems to suggest otherwise.

**Comment by IlyasMoutawwakil** [comment]
These are already "old" benchmarks 😅, the quantization libraries are in constant development, but I believe [this issue still exists in AutoAWQ](https://github.com/casper-hansen/AutoAWQ/issues/246#issuecomment-1848342035). The problem is that GEMV scales very poorly with batch size. If you want the latest benchmarks, I suggest looking at the [llm-perf leaderboard](https://huggingface.co/spaces/optimum/llm-perf-leaderboard) plots.
Quantization schemes that perform compute in fp16 are inherently slower than pure fp16, because of the dequantization overhead. The best way to accelerate an AutoAWQ model is by using its fused modules (`use_fuse=True` in the quant config), which I think delivers the best performance (will add to the llm-perf later).
