### ISSUE TITLE
（question）When I use the memory tracking feature on the GPU, I find that my VRAM is reported as 0. Is this normal, and what might be causing it?

### ISSUE THREAD

**Issue by WCSY-YG** [huggingface/optimum-benchmark#136]
![1](https://github.com/huggingface/optimum-benchmark/assets/89191003/4c1adfad-007b-4ef4-99ff-a43fa0101c00)

**Comment by jhrsya** [comment]
I got this problem too.

**Comment by IlyasMoutawwakil** [comment]
what's your configuration ?

**Comment by WCSY-YG** [comment]
> 你的配置是什么？我无法用我的任何配置重现它



> 你的配置是什么？我无法用我的任何配置重现它

I used an API approach with PyTorch as the backend and passed my own model into the backend.pretrained_model. Subsequently, I got a v_ram value of 0. If there is no v_ram available, can I use max_reserved and max_allocated as references instead?

**Comment by IlyasMoutawwakil** [comment]
The API approach is only guaranteed to work when handled by launch, as it takes care and make sure everything is isolated. otherwise, once you import `PyTorchBackend` for example, torch will be imported, which initializes cuda with all avaialable cuda devices but since `CUDA_DEVICE_ORDER` is not not set, the device ids in `pytorch` and in `pynvml` might end up not referring to the same gpu.
Yes allocated and reserved are good metrics as well, they're measured by pytorch from the inside, reserved counts segments `reserved` from the GPU's memory and `allocated` counts tensors. VRAM is really what you get when you use `nvidia-smi` (outside).

**Comment by WCSY-YG** [comment]
> The API approach is only guaranteed to work when handled by `launch` method, as it takes care of and maked sure everything is isolated. Otherwise, once you import `PyTorchBackend` for example, torch will be imported, which initializes cuda with all avaialable cuda devices but since `CUDA_DEVICE_ORDER` is not not set, the device ids in `pytorch` and in `pynvml` might end up not referring to the same gpu.
> Yes allocated and reserved are good metrics as well, they're measured by pytorch from the inside, `reserved` counts segments reserved from the GPU's memory and `allocated` counts tensors. VRAM is really what you get when you use `nvidia-smi` (outside).


Alright, I understand now, thank you very much for clarifying my doubts! Also, I appreciate that you've designed such a user-friendly tool! One more question, would it be possible for me to utilize the IPEX backend for measurements at this point, since I haven't found a way to import it?

**Comment by IlyasMoutawwakil** [comment]
The IPEX backend is defined in `optimum-intel`, it's still new and seems to replace the INC backend (hence the logging messages). I was planning on adding it once I have some time, but feel free to open a PR, it's a very simple backend (like INC) and should be very straight forward. Ref https://github.com/huggingface/optimum-intel/blob/main/optimum/intel/ipex/modeling_base.py
