### ISSUE TITLE
Is the `test` data generated by random token?

### ISSUE THREAD

**Issue by rui-ren** [huggingface/optimum-benchmark#153]
Hi there, 

I checked the source code and found that, the prompt is generated by random token
![image](https://github.com/huggingface/optimum-benchmark/assets/15321482/d8df67c8-1471-4884-a36b-67e7005c6427)

### Two questions:
- [x] The prompt is from random token.  Am I right?
- [x]  If so, it's okay for inference. However, for training, how we can use dataset e.g. `wikitext` from `datasets` package to test perf? 

Thanks in advance.

**Comment by IlyasMoutawwakil** [comment]
Hello,
- Yes the prompt is random, since in the context of performance benchmarking the actual values don't matter, unless some kind of sparsity optimizations are being used to reduce compute (generally not the case).
- It's also okay for training, you generally have a dataset but you'll probably chunk it / pad it to train the model on a batch of the same length. The metric of interest in the context of training is the number of trained samples per second, which is also independent from the dataset.

However, using a real dataset for inference / training can be interesting in two cases:
- Measuring accuracy or other evaluation related metrics.
- "Training until a loss threshold" which is what the MLPerf do

Currently this is not possible. It can be implemented by abstraction the `input` i.e. `experiment.input=random or dataset`.
The only problem is that when it comes to datasets, there's a different preprocessing for each one, which is hard to maintain.

**Comment by rui-ren** [comment]
Hi @IlyasMoutawwakil , thanks for the details.

I agree that it is hard to maintain the different training jobs, as the datasets need to have different preprocessing. 

Regarding training, this package is for `throughput`, `memory usages` etc. For accuracy, we might turn to `MLPerf`.

Thanks!
