### ISSUE TITLE
[Feature] Add TensorRT benchmark

### ISSUE THREAD

**Issue by jplu** [huggingface/optimum-benchmark#5]
Hi,

First of all thanks a lot for this amazing project.

At some point, it would be interesting to add pure TensorRT benchmark (without passing by ORT) as FP32, FP16, FP8 and INT8.

Let me know if you might find this interesting. I will be happy to help.

**Comment by IlyasMoutawwakil** [comment]
is there a direct way to use the transformers api on tensorrt ?

**Comment by jplu** [comment]
Not as far as I know. What I'm basically doing is to turn a PT model into ONNX with optimum and then turn this ONNX model into TRT.

**Comment by IlyasMoutawwakil** [comment]
For now we're focusing on backends and devices supported through `optimum`. 
With just the ONNX/TRT file you can't perform tasks like text-generation, automatic-speech-recognition, etc. It would only work for feature-extraction at best.
@regisss what do you think ?

**Comment by regisss** [comment]
Yes, I agree with @IlyasMoutawwakil that for now we should restrict ourselves to backends and devices supported by Optimum.

**Comment by x11kjm** [comment]
@IlyasMoutawwakil I agree that static graph compilation methods will not be easily automated. However, as of Torch-TensorRT v1.4.0 there is support for the `torch.compile` workflow in TensorRT which would allow us to invoke the same feature set supported in the Pytorch Eager / compiled Backend: https://github.com/huggingface/optimum-benchmark/blob/main/optimum_benchmark/backends/pytorch.py#L123


The call is similar, yet we use the `torch_tensorrt` package for compilation instead of native Pytorch:
```
import torch_tensorrt
torch_tensorrt.dynamo.compile(model, inputs, ...)
​
##### OR #####
​
torch_tensorrt.compile(model, ir="dynamo_compile", inputs=inputs, ...)
```

Would a solution like this be acceptable? @jplu @regisss

**Comment by regisss** [comment]
@x11kjm Interesting! Would you like to open a PR to add this to Optimum?

@fxmarty WDYT?

**Comment by youssefadr** [comment]
I would like to work on this if it's still needed as a feature
